### ISSUE TITLE
OOP-1-review-2022-10-16

### ISSUE THREAD

**Issue by hamerlinski** [2014Alexander/Programowanie-obiektowe#1]
**Task 1**
- [ ] Proper communication/interaction between classes and objects is missing.
- [ ] Rename repository to **oop-put-course**
- [ ] Rename file to task1.cpp
- [ ] Format code [properly](https://google.github.io/styleguide/cppguide.html)
- [ ] Remove unnecessary files from repository
- [ ] Getters/setters 👎
